### ISSUE TITLE
Your Site Is Down? DNS Problem.

### ISSUE THREAD

**Issue by amark** [jveres/D500px#1]
http://loqali.com/ in Chrome is giving me this error:

```
This site can’t be reached

loqali.com’s server DNS address could not be found.
ERR_NAME_NOT_RESOLVED
```

Sorry I didn't know where else to post this issue.

Hope you're doing well! Just wanted to give you a heads up.

**Comment by jveres** [comment]
Hi! Thanks for the heads up!
It's switched off indeed.

I'm migrating my works under jveres.me, will update the Todos app link as soon as it becomes live again.

Keep up the fantastic work on Gun!

**Comment by amark** [comment]
sweet. thanks, NP! Closing this then.
